name: fbtestplugin
description: A new flutter plugin project.

flutter:
  plugin:
    androidPackage: com.yourcompany.fbtestplugin
    pluginClass: FbtestpluginPlugin

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.11.3+12'
