name: fbtestplugin
description: A new flutter plugin project.

flutter:
  plugin:
    androidPackage: com.yourcompany.fbtestplugin
    pluginClass: FbtestpluginPlugin

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.11.3+12'
  dartson: ">=0.2.0 <0.3.0"

transformers:
- dartson
